services:
  - type: web
    name: myearringadvisor
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn myearringadvisor.wsgi:application --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: myearringadvisor.settings
      - key: DATABASE_URL
        fromDatabase:
          name: myearringadvisor-db
          property: connectionString
      - key: CSRF_TRUSTED_ORIGINS
        sync: false

databases:
  - name: myearringadvisor-db
    databaseName: myearringadvisor
    plan: free
    user: myearringadvisor
